nazwa - dom/wsgi/openshift/microblog/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView
import views

#from .models import Wpis

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.dodaj_wpis, name='add'),
    url(r'^login$', views.zaloguj, name='login'),
    url(r'^logout$', views.wyloguj, name='logout'),
    url(r'^register$', views.rejestracja, name='register'),
    url(r'^mine$', views.moje_wpisy, name='mine'),
    url(r'^filtr$', views.filtruj, name='filtr'),
    url(r'^user/(?P<pk>\d+)$', views.wpisy, name='user'),
)

nazwa - dom/wsgi/openshift/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('microblog.urls', namespace='blog')),
)

nazwa - dom/wsgi/openshift/microblog/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    nick = models.CharField(max_length=20)
    password = models.CharField(('password'), max_length=128)

    def __unicode__(self):
        return self.nick

class Wpis(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=40)
    text = models.TextField('Tekst wpisu')

    def __unicode__(self):
        return self.title

nazwa - dom/wsgi/openshift/microblog/views.py
# -*- coding: utf-8 -*-
from .models import Wpis, User
from django.shortcuts import render_to_response, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def index(request):
    info = request.session.get('info', None)
    if info:
        del request.session['info']
    user_nick = request.session.get('user_nick', None)
    return render_to_response('microblog/main.html', {"wpisy" : Wpis.objects.all().order_by('-pk'), "info" : info, "user_nick" : user_nick})

def dodaj_wpis(request):
    if request.method == 'GET':
        if request.session.get('user_nick', None):
            return render_to_response('microblog/add.html', {"user_nick" : request.session['user_nick']})
        request.session['info'] = u'Najpierw się zaloguj!'
        return HttpResponseRedirect(reverse('blog:login'))

    elif request.method == 'POST':
        title = request.POST['title']
        text = request.POST['text']

        if title and text:
            user = User.objects.get(nick=request.session['user_nick'])

            w = Wpis(title=title, text=text)
            w.author = user
            w.save()

            request.session['info'] = u'Dodano wpis!'
            return HttpResponseRedirect(reverse('blog:index'))

def zaloguj(request):
    info = request.session.get('info', None)

    if request.method == 'GET':
        if request.session.get('user_nick', None):
            request.session['info'] = u'Jesteś już zalogowany!'
            return HttpResponseRedirect(reverse('blog:index'))
        return render_to_response('microblog/login.html', {"info" : info})

    elif request.method == 'POST':
        nick = request.POST['nick']
        password = request.POST['password']

        userzy = User.objects.all()
        for user in userzy:
            if user.nick == nick and user.password == password:
                request.session['user_nick'] = user.nick
                request.session['info'] = u'Zostałeś zalogowany!'
                return HttpResponseRedirect(reverse('blog:index'))
        request.session['info'] = u'Błędne dane!'
        return HttpResponseRedirect(reverse('blog:login'))

def wyloguj(request):
    #wylogowanie
    if request.session['user_nick']:
        del request.session['user_nick']
    request.session['info'] = u'Zostałeś wylogowany!'
    return HttpResponseRedirect(reverse('blog:index'))

def rejestracja(request):
    info = request.session.get('info', None)

    if request.method == 'GET':
        if request.session.get('user_nick', None):
            request.session['info'] = u'Jesteś już zarejestrowany!'
            return HttpResponseRedirect(reverse('blog:index'))
        return render_to_response('microblog/register.html', {"info" : info})
    elif request.method == 'POST':
        #sprawdzanie poprawnosci
        nick = request.POST['nick']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if pass1 and pass2 and nick:
            userzy = User.objects.all()
            for user in userzy:
                if user.nick == nick:
                    request.session['info'] = u'Podany login jest już zajęty!'
                    return HttpResponseRedirect(reverse('blog:register'))

            if pass1 == pass2:
                u = User(nick=nick, password=pass1)
                u.save()
                request.session['info'] = u'Rejestracja zakończona pomyślnie. Możesz się zalogować!'
                return HttpResponseRedirect(reverse('blog:index'))
            else:
                request.session['info'] = u'Hasła są różne!'
                return HttpResponseRedirect(reverse('blog:register'))
        else:
            request.session['info'] = u'Wypełnij wszystkie pola!'
            return HttpResponseRedirect(reverse('blog:register'))

def moje_wpisy(request):
    if request.session.get('user_nick', None):
        author = User.objects.get(nick=request.session['user_nick'])
        wpisy = Wpis.objects.all().order_by('-pk').filter(author=author)
        return render_to_response('microblog/mine.html', {"wpisy" : wpisy, "user_nick" : request.session['user_nick']})
    else:
        request.session['info'] = u'Najpierw się zaloguj!'
        return HttpResponseRedirect(reverse('blog:login'))

def filtruj(request):
    users = User.objects.all().order_by('nick')
    return render_to_response('microblog/users.html', {"users" : users, "user_nick" : request.session.get('user_nick', None)})

def wpisy(request, pk):
    try:
        user = User.objects.get(pk=pk)
    except:
        return render_to_response('microblog/users_posts.html', {"wpisy" : None, 'user' : None})
    wpisy = Wpis.objects.all().filter(author_id=pk).order_by('-pk')
    return render_to_response('microblog/users_posts.html', {"wpisy" : wpisy, 'user' : user, "user_nick" : request.session.get('user_nick', None)})

nazwa - dom/wsgi/openshift/views.py
from django.shortcuts import render_to_response

def home(request):
     return render_to_response('home/home.html')

nazwa - dom/wsgi/openshift/microblog/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Microblog DJANGO</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'microblog/style.css' %}" />
    </head>
    <body>
    <h1>Microblog</h1>
    {% if info %}
        <p class="info"> {{ info }}</p>
    {% endif %}
    {% if user_nick %}
        <p><b>Jesteś zalogowany jako:</b> {{ user_nick }}</p>
    {% endif %}
    <div class="menu">
    <ul class="nav">
            <li><a href="{% url 'blog:index' %}">Strona główna</a></li>
    {% if user_nick %}
            <li><a href="{% url 'blog:logout' %}">Wyloguj się</a></li>
            <li><a href="{% url 'blog:add' %}">Dodaj wpis</a></li>
            <li><a href="{% url 'blog:mine' %}">Twoje wpisy</a></li>
            {% else %}
            <li><a href="{% url 'blog:login' %}">Zaloguj się</a></li>
            <li><a href="{% url 'blog:register' %}">Rejestracja</a></li>
    {% endif %}
            <li><a href="{% url 'blog:filtr' %}">Wpisy użytkowników</a></li>
    </ul>
    </div>

    {% block content %}
    {% endblock %}
    </body>
</html>

nazwa - dom/wsgi/openshift/microblog/templates/microblog/add.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'blog:add' %}" method="POST">
    <div>
        <label for="title">Tytuł:</label><br/>
        <input type="text" id="title" name="title"/>
    </div>
    <div>
        <label for="text">Tekst:</label><br/>
        <textarea name="text" id="text" cols="40" rows="5" style="resize: none;"></textarea>
    </div>
    <div>
        <input type="submit" value="Dodaj"/>
    </div>
</form>
{% endblock %}

nazwa - dom/wsgi/openshift/microblog/templates/microblog/login.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'blog:login' %}" method="POST">
    <div><label>Login:</label>
    <input type="text" name="nick"/></div>
    <div><label>Hasło:</label>
    <input type="password" name="password"/></div>
    <input type="submit" value="Zaloguj">
</form>
{% endblock %}

nazwa - dom/wsgi/openshift/microblog/templates/microblog/main.html
{% extends "base.html" %}

{% block content %}
{% if wpisy %}
        {% for wpis in wpisy %}
        <div class="wpis">
                <div class="author">{{ wpis.author.nick }}</div>
                <div class="title">{{ wpis.title }}</div>
                <div class="text">{{ wpis.text }}</div>
        </div>
        {% endfor %}
{% else %}
        <h4>Aktualnie brak wpisów</h4>
{% endif %}
{% endblock %}

nazwa - dom/wsgi/openshift/microblog/templates/microblog/mine.html
{% extends "base.html" %}

{% block content %}
{% if wpisy %}
        <h4>Twoje wpisy:</h4>
        {% for wpis in wpisy %}
        <div class="wpis">
            <div class="title">{{ wpis.title }}</div>
            <div class="text">{{ wpis.text }}</div>
        </div>
        {% endfor %}
{% else %}
        <h4>Aktualnie brak Twoich wpisów</h4>
{% endif %}
{% endblock %}

nazwa - dom/wsgi/openshift/microblog/templates/microblog/register.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'blog:register' %}" method="POST">
    <div><label>Login:</label>
    <input type="text" id="nick" name="nick"/></div>
    <div><label>Hasło:</label>
    <input type="password" id="pass1" name="pass1"/></div>
    <div><label>Powtórz hasło:</label>
    <input type="password" id="pass2" name="pass2"/></div>
    <input type="submit" value="Zarejestruj">
</form>
{% endblock %}

nazwa - dom/wsgi/openshift/microblog/templates/microblog/users.html
{% extends "base.html" %}

{% block content %}
{% if users %}
        <h3>Wybierz użytkownika:</h3>
        <div class="list">
        {% for user in users %}
            <p><a href="{% url 'blog:user' user.pk %}">{{ user.nick }}</a></p>
        {% endfor %}
        </div>
{% else %}
        <h3>Aktualnie brak użytkowników</h3>
{% endif %}
{% endblock %}

nazwa - dom/wsgi/openshift/microblog/templates/microblog/users_posts.html
{% extends "base.html" %}

{% block content %}
{% if wpisy %}
        <h3>Wpisy użytkownika {{ user }}:</h3>
        {% for wpis in wpisy %}
        <div class="wpis">
                <div class="author">{{ wpis.author.nick }}</div>
                <div class="title">{{ wpis.title }}</div>
                <div class="text">{{ wpis.text }}</div>
        </div>
        {% endfor %}
{% else %}
<h3>Brak wpisów dla tego użytkownika</h3>
{% endif %}
{% endblock %}

nazwa - dom/wsgi/openshift/templates/home/home.html
<b>Congrats you have Django 1.6 running on OpenShift!<b>
<br />
let's <a href="/admin">admin </a>
<br />
Enjoy!!! 